platform :ios, '8.0'
use_frameworks!

target 'Operator' do
  pod 'Masonry', '~> 1.0.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.10'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'SDCycleScrollView', '~> 1.64'#轮播器
  pod 'IQKeyboardManager'#用于键盘管理
  pod 'GJCFUitils'#各种常用宏的集合
  pod 'JPush-iOS-SDK', '~> 2.1.7'
  pod 'UMengSocialCOM', '~> 5.2.1'
  pod 'SDCycleScrollView','~> 1.64'
  pod 'CocoaAsyncSocket', '~> 7.4.3'
  pod 'TZImagePickerController', '~> 1.4.4'
end
